---
# tasks file for apache
#hosts: Web_server


- name: Installing httpd software
  package:
         name: httpd
         state: present

- name: Installing PHP interpreter
  package:
         name: php
         state: present

- name: Copying content of Web server
  copy:
      content: '<pre>
               <?php
               print`/usr/sbin/ifconfig enp0s3`;
                ?>
              </pre>'
      dest: /var/www/html/index.php
  notify:
       - Restart httpd

       
  
